// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package setup

import (
	"context"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/dave/dst"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
	"golang.org/x/mod/semver"
	"gopkg.in/yaml.v3"

	"go.opentelemetry.io/otelc/tool/ex"
	"go.opentelemetry.io/otelc/tool/internal/ast"
	"go.opentelemetry.io/otelc/tool/internal/pkgload"
	"go.opentelemetry.io/otelc/tool/internal/rule"
	"go.opentelemetry.io/otelc/tool/util"
)

func removeImports(f *dst.File, importPaths map[string]bool) error {
	decls := make([]dst.Decl, 0, len(f.Decls))

	for _, decl := range f.Decls {
		genDecl, isGenDecl := decl.(*dst.GenDecl)
		if !isGenDecl || genDecl.Tok != token.IMPORT {
			decls = append(decls, decl)
			continue
		}

		specs := genDecl.Specs[:0]
		for _, spec := range genDecl.Specs {
			importSpec, isImportSpec := spec.(*dst.ImportSpec)
			if !isImportSpec {
				specs = append(specs, spec)
				continue
			}

			path, err := strconv.Unquote(importSpec.Path.Value)
			if err != nil {
				return ex.Wrapf(err, "failed to unquote import path %s", importSpec.Path.Value)
			}

			// skip the import we want to remove
			if _, removeImport := importPaths[path]; removeImport {
				continue
			}

			specs = append(specs, spec)
		}

		if len(specs) == 0 {
			// entire import decl became empty
			continue
		}

		genDecl.Specs = specs
		decls = append(decls, genDecl)
	}

	f.Decls = decls
	return nil
}

func generateDirective(opts PinOptions) string {
	args := []string{
		"//go:generate",
		"go",
		"tool",
		util.OtelcToolExe,
		"pin",
		"--generate",
	}

	if !opts.Prune {
		args = append(args, "--prune=false")
	}
	if opts.Validate {
		args = append(args, "--validate")
	}

	return strings.Join(args, " ")
}

func updateGenerateDirective(f *dst.File, opts PinOptions) {
	// Nothing passed? Do not touch the directive at all.
	if opts.Generate == nil {
		return
	}

	comments := make([]string, 0, len(f.Decs.Start.All()))
	for _, comment := range f.Decs.Start.All() {
		// Drop any existing otelc pin directive. We will either
		// regenerate it or remove it entirely.
		const goGenerateDirectivePrefix = "//go:generate go tool " + util.OtelcToolExe + " pin"
		if strings.HasPrefix(comment, goGenerateDirectivePrefix) {
			continue
		}

		comments = append(comments, comment)
	}

	if *opts.Generate {
		comments = append(comments, generateDirective(opts))
	}

	f.Decs.Start.Clear()
	f.Decs.Start.Append(comments...)
}

func generateOtelInstrumentationGo(imports map[string]bool, opts PinOptions) *dst.File {
	// Create a slice of import paths and sort them
	importPaths := make([]string, 0, len(imports))
	for path := range imports {
		importPaths = append(importPaths, path)
	}
	slices.Sort(importPaths)

	// Use the sorted import paths to create import specs
	importSpecs := make([]dst.Spec, 0, len(importPaths))
	for _, path := range importPaths {
		importSpecs = append(importSpecs, &dst.ImportSpec{
			Name: ast.Ident(ast.IdentIgnore),
			Path: &dst.BasicLit{
				Kind:  token.STRING,
				Value: strconv.Quote(path),
			},
		})
	}

	comments := ast.LineComments(
		"// This file is automatically generated by otelc pin for tracking instrumentations.",
		"// Additional instrumentation imports may be added manually.",
		"\n",
		"//go:build tools",
	)

	// If generate is explicitly enabled, or not set at all, include the //go:generate directive.
	if opts.Generate == nil || *opts.Generate {
		comments.Start.Append(generateDirective(opts))
	}

	return &dst.File{
		Name: ast.Ident("tools"),
		Decs: dst.FileDecorations{
			NodeDecs: comments,
		},
		Decls: []dst.Decl{
			&dst.GenDecl{
				Tok:   token.IMPORT,
				Specs: importSpecs,
			},
		},
	}
}

type yamlRule struct {
	Target       string `yaml:"target"`
	VersionRange string `yaml:"version"`
}

func loadModuleRules(moduleDir, module string, loaded map[string][]yamlRule) error {
	return filepath.WalkDir(moduleDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			// Skip any submodules
			if path != moduleDir && util.PathExists(filepath.Join(path, "go.mod")) {
				return filepath.SkipDir
			}
			return nil
		}

		if !isRuleFile(d.Name()) {
			return nil
		}

		data, readErr := os.ReadFile(path) //nolint:gosec // walking embedded rules from extractOtelcBundle
		if readErr != nil {
			return ex.Wrapf(readErr, "reading rule file %s", path)
		}

		var rules map[string]yamlRule
		if unmarshalErr := yaml.Unmarshal(data, &rules); unmarshalErr != nil {
			return ex.Wrapf(unmarshalErr, "parsing rule file %s", path)
		}

		for _, r := range rules {
			if r.Target != "" {
				loaded[module] = append(loaded[module], r)
			}
		}

		return nil
	})
}

func loadMinimalRules(rulesRoot string) (map[string][]yamlRule, error) {
	loaded := make(map[string][]yamlRule)

	err := filepath.WalkDir(rulesRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		// rulesRoot is instrumentation/
		// We want to load rules for submodules within instrumentation/
		// Look for go.mod nested within instrumentation/
		if d.IsDir() || d.Name() != "go.mod" || filepath.Dir(path) == rulesRoot {
			return nil
		}

		modFile, err := parseGoMod(path)
		if err != nil {
			return ex.Wrapf(err, "loading %s", path)
		}

		return loadModuleRules(filepath.Dir(path), modFile.Module.Mod.Path, loaded)
	})
	if err != nil {
		return nil, err
	}

	return loaded, nil
}

func ensureOtelcRequireVersion(f *modfile.File, version string) (bool, error) {
	if !semver.IsValid(version) || version == "v0.0.0" || module.IsPseudoVersion(version) {
		return false, nil
	}

	for _, req := range f.Require {
		if req.Mod.Path != util.OtelcRoot {
			continue
		}

		if semver.Compare(req.Mod.Version, version) >= 0 {
			return false, nil
		}
		break
	}

	if err := f.AddRequire(util.OtelcRoot, version); err != nil {
		return false, err
	}

	return true, nil
}

func ensureOtelcRequire(moduleDir, version string) (bool, error) {
	goModPath := filepath.Join(moduleDir, "go.mod")
	data, err := os.ReadFile(goModPath)
	if err != nil {
		return false, err
	}

	f, err := modfile.Parse(goModPath, data, nil)
	if err != nil {
		return false, err
	}

	modified := false

	hasTool := false
	for _, tool := range f.Tool {
		if tool.Path == util.OtelcToolCmdRoot {
			hasTool = true
			break
		}
	}

	if !hasTool {
		if addErr := f.AddTool(util.OtelcToolCmdRoot); addErr != nil {
			return false, addErr
		}
		modified = true
	}

	added, ensureErr := ensureOtelcRequireVersion(f, version)
	if ensureErr != nil {
		return false, ensureErr
	}
	modified = modified || added

	if !modified {
		return false, nil
	}

	if writeErr := writeGoMod(goModPath, f); writeErr != nil {
		return false, writeErr
	}

	return true, nil
}

func matchInstrumentationImports(deps []*Dependency, ruleset map[string][]yamlRule) map[string]bool {
	imports := make(map[string]bool)

	// Match only on target + version.
	for _, dep := range deps {
		for modPath, rules := range ruleset {
			for _, r := range rules {
				switch {
				case rule.IsRootTarget(r.Target):
					// always add root targets
					// they will be further matched in setup phase
					imports[modPath] = true
					continue
				case rule.IsGlobTarget(r.Target):
					if !rule.MatchGlobTarget(r.Target, dep.ImportPath) {
						continue
					}
				case r.Target != dep.ImportPath:
					continue
				}

				if !util.VersionInRange(dep.Version, r.VersionRange) {
					continue
				}

				imports[modPath] = true
			}
		}
	}

	return imports
}

func updateToolFile(ctx context.Context, toolFile string, prunedImports map[string]bool, opts PinOptions) error {
	p := ast.NewAstParser()

	f, parseErr := p.Parse(toolFile, parser.ParseComments)
	if parseErr != nil {
		return ex.Wrapf(parseErr, "parsing tool file %s", toolFile)
	}

	if len(prunedImports) > 0 {
		if removeErr := removeImports(f, prunedImports); removeErr != nil {
			return ex.Wrapf(removeErr, "removing imports from %s", toolFile)
		}
	}

	updateGenerateDirective(f, opts)

	if writeErr := ast.WriteFileAtomic(toolFile, f); writeErr != nil {
		return writeErr
	}

	_, ensureErr := ensureOtelcRequire(filepath.Dir(toolFile), util.Version)
	if ensureErr != nil {
		return ex.Wrapf(ensureErr, "ensuring otelc require in go.mod in %s", filepath.Dir(toolFile))
	}

	if tidyErr := runModTidy(ctx, filepath.Dir(toolFile)); tidyErr != nil {
		return ex.Wrapf(tidyErr, "running go mod tidy in %s", filepath.Dir(toolFile))
	}

	return nil
}

func updatePinnedProjects(
	ctx context.Context,
	toolFiles []string,
	opts PinOptions,
) (*PinResult, error) {
	logger := util.LoggerFromContext(ctx)
	prunedImports := make(map[string]map[string]bool, len(toolFiles))

	walkErr := walkInstrumentation(ctx, toolFiles,
		func(v *InstrumentationVisit) (bool, error) {
			pruneImport := func(reason error) {
				logger.WarnContext(ctx, "invalid instrumentation import",
					"importPath", v.Config.ImportPath,
					"toolFile", v.ToolFile,
					"reason", reason)
				_, _ = fmt.Fprintf(
					os.Stderr,
					"Invalid instrumentation import %s from %s: %v\n",
					v.Config.ImportPath,
					v.ToolFile,
					reason,
				)

				// We only prune imports from root tool files.
				if opts.Prune && slices.Contains(toolFiles, v.ToolFile) {
					if prunedImports[v.ToolFile] == nil {
						prunedImports[v.ToolFile] = make(map[string]bool)
					}
					prunedImports[v.ToolFile][v.Config.ImportPath] = true
				}
			}

			if v.Config.Error != nil {
				if errors.Is(v.Config.Error, ErrNotInstrumentation) {
					pruneImport(v.Config.Error)
					return false, nil
				}

				// Environment/module resolution problem.
				return false, v.Config.Error
			}

			// Also validate that all rule files in the import are valid.
			if opts.Validate {
				for _, ruleFile := range v.Config.RuleFiles {
					content, readErr := os.ReadFile(ruleFile)
					if readErr != nil {
						return false, ex.Wrapf(readErr, "reading %s", ruleFile)
					}

					if _, parseErr := parseRuleFromYaml(content); parseErr != nil {
						pruneImport(parseErr)
						return false, nil
					}
				}
			}

			// Always recurse into nested tool files when they exist.
			return true, nil
		},
	)
	if walkErr != nil {
		return nil, walkErr
	}

	for _, toolFile := range toolFiles {
		if err := updateToolFile(ctx, toolFile, prunedImports[toolFile], opts); err != nil {
			return nil, err
		}
	}

	return &PinResult{}, nil
}

func generatePinnedProjects(ctx context.Context, moduleDirs map[string]bool, opts PinOptions) (*PinResult, error) {
	logger := util.LoggerFromContext(ctx)
	subcommand := opts.Subcommand
	if subcommand == "" {
		subcommand = subcmdBuild
	}

	// No tool file found? Try generating one.
	deps, findDepsErr := findDeps(ctx, subcommand, opts.Args)
	if findDepsErr != nil {
		return nil, ex.Wrapf(findDepsErr, "finding dependencies")
	}

	extractErr := extractOtelcBundle()
	if extractErr != nil {
		return nil, ex.Wrapf(extractErr, "extracting otelc package")
	}

	ruleset, err := loadMinimalRules(filepath.Join(util.GetBuildTempDir(), unzippedInstDir))
	if err != nil {
		return nil, ex.Wrapf(err, "loading instrumentation rules")
	}

	// We expect every built-in instrumentation module to be importable
	imports := matchInstrumentationImports(deps, ruleset)

	// Nothing to instrument? Warn and skip generating tool file.
	if len(imports) == 0 {
		_, _ = fmt.Fprintf(
			os.Stderr,
			"Warning: no instrumentations matched, checked %d dependencies. Skipping generating %s file.\n",
			len(deps),
			ToolFileCanonical,
		)
		logger.WarnContext(ctx, "no instrumentations matched, skipping generating tool file")

		// Ok to re-use deps here, because we do not run "go mod tidy".
		return &PinResult{AllDeps: deps}, nil
	}

	// Generate otel.instrumentation.go file with imports for all matched rules.
	f := generateOtelInstrumentationGo(imports, opts)
	for moduleDir := range moduleDirs {
		path := filepath.Join(moduleDir, ToolFileCanonical)
		if writeErr := ast.WriteFileAtomic(path, f); writeErr != nil {
			return nil, ex.Wrapf(writeErr, "writing %s", path)
		}

		if _, ensureErr := ensureOtelcRequire(moduleDir, util.Version); ensureErr != nil {
			return nil, ex.Wrapf(ensureErr, "ensuring otelc require in go.mod in %s", moduleDir)
		}

		if syncErr := syncDeps(ctx, imports, moduleDir); syncErr != nil {
			return nil, ex.Wrapf(syncErr, "syncing dependencies in %s", moduleDir)
		}

		keepForDebug(ctx, path)
	}

	// Intentionally return an empty PinResult
	// Since we ran syncDeps, the dependencies may have been updated
	// Therefore, we want to ensure we rerun findDeps in setup phase.
	return &PinResult{}, nil
}

func prepareVendoredBuild(ctx context.Context, logger *slog.Logger, args []string) ([]string, error) {
	if !vendoringActive(ctx, util.GetOtelcWorkDir()) {
		return args, nil
	}

	logger.InfoContext(ctx, "vendored project detected; building with -mod=mod")

	if err := os.Setenv("GOFLAGS", forceModMod(os.Getenv("GOFLAGS"))); err != nil {
		return nil, ex.Wrapf(err, "forcing module mode for vendored build")
	}

	return rewriteModVendor(args), nil
}

type PinOptions struct {
	// Whether to prune invalid imports within otel.instrumentation.go
	Prune bool
	// Whether to validate that all imports in otel.instrumentation.go contain valid rule
	Validate bool
	// Whether to have a //go:generate directive in otel.instrumentation.go
	Generate *bool
	// Args passed to go build/install/test in findDeps
	Args []string
	// Subcommand passed to go in findDeps (defaults to "build")
	Subcommand string
	// ModuleDirs is the set of module directories to search for tool files
	// If empty, module directories will be found using opts.Args
	ModuleDirs map[string]bool
}

type PinResult struct {
	// AllDeps is a list of all dependencies found in the project (not just those with instrumentation).
	// It may not be always present, this can be used by later stages (setup) instead of
	// re-parsing compile commands again.
	AllDeps []*Dependency
}

// Pin generates or updates otel.instrumentation.go to pin instrumentation packages for the current module.
// It also returns a PinResult, which may optionally include a list of all dependencies found in the project
// (not just those with instrumentation). The PinResult can be used by later stages (setup) instead of
// re-parsing compile commands again.
func Pin(ctx context.Context, opts PinOptions) (*PinResult, error) {
	var result *PinResult
	err := withBuildLock(ctx, func(ctx context.Context) error {
		var pinErr error
		result, pinErr = pinLocked(ctx, opts)
		return pinErr
	})
	return result, err
}

func pinLocked(ctx context.Context, opts PinOptions) (*PinResult, error) {
	moduleDirs := opts.ModuleDirs
	// moduleDirs being empty means Pin was invoked as a standalone command
	// (not as part of a setup run), so use opts.Args to find module directories.
	if len(moduleDirs) == 0 {
		// For same reason as Setup, we have to check vendoring state before
		// forcing module mode and rewriting vendor/ paths to module mode.
		args, err := prepareVendoredBuild(ctx, util.LoggerFromContext(ctx), opts.Args)
		if err != nil {
			return nil, ex.Wrapf(err, "preparing vendored build")
		}
		opts.Args = args

		// Use opts.Args to find module directories
		pkgs, getErr := getBuildPackages(ctx, opts.Args)
		if getErr != nil {
			return nil, ex.Wrapf(getErr, "getting build packages")
		}

		moduleDirs, err = pkgload.FindModuleDirs(ctx, pkgs)
		if err != nil {
			return nil, ex.Wrapf(err, "finding module directories")
		}
	}

	toolFiles, findToolErr := findToolFiles(moduleDirs)
	if findToolErr != nil {
		return nil, findToolErr
	}

	// Existing otel.instrumentation.go / otelc.tool.go files found?
	// Validate and update them in-place.
	if len(toolFiles) > 0 {
		return updatePinnedProjects(ctx, toolFiles, opts)
	}

	// Otherwise, infer instrumentations from the dependency graph and
	// generate fresh tool files.
	return generatePinnedProjects(ctx, moduleDirs, opts)
}

// AutoPin is a convenience function that automatically tracks generated/modified files before calling Pin
// in order to restore them after the build completes.
func AutoPin(ctx context.Context, moduleDirs map[string]bool, subcommand string, args []string) (*PinResult, error) {
	stateManager, found := StateManagerFromContext(ctx)
	if !found {
		return nil, ex.New("state manager not found in context")
	}

	backupFiles, getBackupErr := getBackupFiles(ctx, moduleDirs)
	if getBackupErr != nil {
		return nil, ex.Wrapf(getBackupErr, "getting backup files")
	}
	if trackErr := stateManager.TrackAll(backupFiles...); trackErr != nil {
		return nil, ex.Wrapf(trackErr, "tracking backup files")
	}

	pinResult, pinErr := Pin(ctx, PinOptions{
		Prune:      true,
		Args:       args,
		Subcommand: subcommand,
		ModuleDirs: moduleDirs,
	})

	return pinResult, pinErr
}
